services:
  web:
    build: .
    command: >
      sh -c "python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
      - ollama

  ollama:
    image: ollama/ollama
    entrypoint: /bin/bash /entrypoint.sh
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ollama_data:/root/.ollama

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=superstrongpassword
      - POSTGRES_USER=postgres

volumes:
  postgres_data:
  ollama_data:
