name: intergration checks

on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test User
        run: docker compose run web python app/manage.py test user
      - name: Test Formatter
        run: docker compose run web python app/manage.py test formatter
